#spring.config.import=optional:file:.env[.properties]
spring.application.name=auth-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.jpa.open-in-view=false


server.port=${SERVER_PORT}

# JWT settings consumed by JwtService
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Frontend OAuth2 redirect URL
application.oauth2.frontend-redirect-url=${OAUTH2_FRONTEND_REDIRECT_URL}

# API Gateway CORS allowed origins
application.api-gateway.allowed-origins=${API_GATEWAY_ORIGINS:}

# Eureka Service Registry URL
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


