# Local profile: MySQL
spring.datasource.url=${MYSQL_DB_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Frontend URL for local development
application.oauth2.frontend-redirect-url=http://localhost:3000/oauth2/redirect

# API Gateway CORS origins for local development
application.api-gateway.allowed-origins=${API_GATEWAY_ORIGINS}
