app.repository.type=database

app.datasource.driverClassName=com.mysql.cj.jdbc.Driver
app.datasource.url=jdbc:mysql://localhost:3306/QuantityMeasurementDb?createDatabaseIfNotExist=true
app.datasource.username=root
app.datasource.password=Sanju@123

app.datasource.pool.initialSize=2
app.datasource.pool.maxSize=10
app.datasource.pool.connectionTimeoutMillis=5000

app.datasource.schemaLocation=db/schema.sql

logging.level.com.example=INFO
